package com.madhukar.upisplitter.service;
import com.madhukar.upisplitter.dto.ApiDtos.*; import com.madhukar.upisplitter.model.*; import com.madhukar.upisplitter.repository.*; import org.springframework.stereotype.Service; import java.math.*; import java.time.*; import java.util.*; import java.util.stream.*;
@Service public class AnalyticsService {
 private final PaymentPlanRepository plans; private final PaymentTransactionRepository txns; private final UserService users;
 public AnalyticsService(PaymentPlanRepository p,PaymentTransactionRepository t,UserService u){plans=p;txns=t;users=u;}
 public Summary summary(String uid){List<PaymentTransaction> l=txns.findByUserIdOrderByCreatedAtDesc(uid);long s=l.stream().filter(x->x.getStatus()==PaymentTransaction.Status.SUCCESS).count(),p=l.stream().filter(x->x.getStatus()==PaymentTransaction.Status.PENDING).count(),f=l.stream().filter(x->x.getStatus()==PaymentTransaction.Status.FAILED).count();BigDecimal v=l.stream().map(PaymentTransaction::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal avg=l.isEmpty()?BigDecimal.ZERO:v.divide(BigDecimal.valueOf(l.size()),2,RoundingMode.HALF_UP);return new Summary(plans.countByUserId(uid),l.size(),s,p,f,v,l.isEmpty()?0:Math.round(s*10000.0/l.size())/100.0,avg);}
 public List<StatusCount> status(String uid){return Arrays.stream(PaymentTransaction.Status.values()).map(s->new StatusCount(s.name(),txns.findByUserIdOrderByCreatedAtDesc(uid).stream().filter(x->x.getStatus()==s).count())).toList();}
 public List<DailyCount> daily(String uid){Map<LocalDate,List<PaymentTransaction>> m=txns.findByUserIdOrderByCreatedAtDesc(uid).stream().collect(Collectors.groupingBy(x->x.getCreatedAt().atZone(ZoneId.systemDefault()).toLocalDate(),TreeMap::new,Collectors.toList()));return m.entrySet().stream().map(e->new DailyCount(e.getKey().toString(),e.getValue().size(),e.getValue().stream().map(PaymentTransaction::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add))).toList();}
public List<AmountCount> amounts(String uid){return txns.findByUserIdOrderByCreatedAtDesc(uid).stream().collect(Collectors.groupingBy(x->x.getAmount().toPlainString(),Collectors.counting())).entrySet().stream().sorted(Map.Entry.comparingByKey()).map(e->new AmountCount(e.getKey(),e.getValue())).toList();}
  public AdminStats admin(){long u=users.count(),p=plans.count(),t=txns.count();List<PaymentTransaction> l=txns.findAll();long s=l.stream().filter(x->x.getStatus()==PaymentTransaction.Status.SUCCESS).count(),pe=l.stream().filter(x->x.getStatus()==PaymentTransaction.Status.PENDING).count(),f=l.stream().filter(x->x.getStatus()==PaymentTransaction.Status.FAILED).count();BigDecimal v=l.stream().map(PaymentTransaction::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);return new AdminStats(u,p,t,s,pe,f,v);}
}
