package com.madhukar.upisplitter.service;
import com.madhukar.upisplitter.dto.PaymentDtos.*; import com.madhukar.upisplitter.exception.ApiException; import com.madhukar.upisplitter.model.*; import com.madhukar.upisplitter.model.PaymentPlan.PlanStatus; import com.madhukar.upisplitter.model.PaymentTransaction.Status; import com.madhukar.upisplitter.repository.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import java.math.*; import java.time.Instant; import java.util.*; import com.madhukar.upisplitter.util.PaymentSplitter;
@Service public class PaymentPlanService {
 private final PaymentPlanRepository plans; private final PaymentTransactionRepository txns; private final PaymentProvider provider; private final AuditService audit;
 public PaymentPlanService(PaymentPlanRepository p,PaymentTransactionRepository t,PaymentProvider provider,AuditService audit){this.plans=p;this.txns=t;this.provider=provider;this.audit=audit;}
 public PlanResponse create(String userId,CreatePlanRequest r){if(!r.receiverType().equals("UPI_ID") && !r.receiverType().equals("MOBILE"))throw new ApiException(HttpStatus.BAD_REQUEST,"Receiver type must be UPI_ID or MOBILE");if(r.receiverType().equals("UPI_ID") && !r.receiver().matches("^[A-Za-z0-9._-]{2,}@[A-Za-z0-9._-]{2,}$"))throw new ApiException(HttpStatus.BAD_REQUEST,"Enter a valid UPI ID, for example merchant@bank");if(r.receiverType().equals("MOBILE") && !r.receiver().matches("^\\+?[0-9]{10,15}$"))throw new ApiException(HttpStatus.BAD_REQUEST,"Enter a valid mobile number");if(r.maxPerPayment().compareTo(r.totalAmount())>0)throw new ApiException(HttpStatus.BAD_REQUEST,"Maximum payment amount cannot exceed total amount");List<BigDecimal> amounts; try{amounts=PaymentSplitter.split(r.totalAmount(),r.maxPerPayment());}catch(IllegalArgumentException e){throw new ApiException(HttpStatus.BAD_REQUEST,e.getMessage());}
  String order="PLAN-"+UUID.randomUUID().toString().substring(0,8).toUpperCase();Instant now=Instant.now();PaymentPlan plan=plans.save(PaymentPlan.builder().userId(userId).orderId(order).totalAmount(r.totalAmount()).maxPerPayment(r.maxPerPayment()).numberOfPayments(amounts.size()).description(r.description()).receiverType(r.receiverType()).receiver(r.receiver()).receiverName(r.receiverName()).status(PlanStatus.PENDING).createdAt(now).updatedAt(now).build());
  List<PaymentTransaction> txs=new ArrayList<>();for(int i=0;i<amounts.size();i++){PaymentTransaction x=PaymentTransaction.builder().paymentPlanId(plan.getId()).userId(userId).sequence(i+1).amount(amounts.get(i)).status(Status.PENDING).createdAt(now).updatedAt(now).build();txs.add(x);}txs=txns.saveAll(txs);for(PaymentTransaction x:txs){x.setQrPayload(provider.createUpiPayload(x.getId(),plan.getId(),x.getAmount(),plan.getReceiverType(),plan.getReceiver(),plan.getReceiverName()));}txns.saveAll(txs);audit.log(userId,"CREATE_PAYMENT_PLAN","PAYMENT_PLAN",plan.getId(),Map.of("orderId",order));return response(plan,txs);
 }
 public List<PlanResponse> list(String userId){return plans.findByUserIdOrderByCreatedAtDesc(userId).stream().map(p->response(p,txns.findByPaymentPlanIdOrderBySequenceAsc(p.getId()))).toList();}
 public PlanResponse get(String userId,String id){PaymentPlan p=plans.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Payment plan not found"));if(!p.getUserId().equals(userId))throw new ApiException(HttpStatus.FORBIDDEN,"Access denied");return response(p,txns.findByPaymentPlanIdOrderBySequenceAsc(id));}
 public StatusResponse changeStatus(String userId,String id,Status target){PaymentTransaction x=txns.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Payment not found"));if(!x.getUserId().equals(userId))throw new ApiException(HttpStatus.FORBIDDEN,"Access denied");if(x.getStatus()!=Status.PENDING)throw new ApiException(HttpStatus.CONFLICT,"Payment status has already been finalized");Instant now=Instant.now();x.setStatus(target);x.setUpdatedAt(now);x.setCompletedAt(now);txns.save(x);PaymentPlan p=plans.findById(x.getPaymentPlanId()).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Payment plan not found"));List<PaymentTransaction> all=txns.findByPaymentPlanIdOrderBySequenceAsc(p.getId());long success=all.stream().filter(t->t.getStatus()==Status.SUCCESS).count(), failed=all.stream().filter(t->t.getStatus()==Status.FAILED).count();long pending=all.size()-success-failed;if(success==all.size())p.setStatus(PlanStatus.COMPLETED);else if(success>0&&failed>0)p.setStatus(PlanStatus.PARTIALLY_COMPLETED);else if(failed>0&&pending>0)p.setStatus(PlanStatus.FAILED);else if(failed==all.size())p.setStatus(PlanStatus.FAILED);else p.setStatus(PlanStatus.PENDING);p.setUpdatedAt(now);plans.save(p);audit.log(userId,"SIMULATE_"+target.name(),"PAYMENT_TRANSACTION",x.getId(),Map.of("status",target.name()));return new StatusResponse("Payment "+x.getId()+" marked as "+target.name().toLowerCase()+".",item(x),p.getStatus());}
 public void delete(String userId,String id){PaymentPlan p=plans.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Payment plan not found"));if(!p.getUserId().equals(userId))throw new ApiException(HttpStatus.FORBIDDEN,"Access denied");txns.deleteAll(txns.findByPaymentPlanIdOrderBySequenceAsc(id));plans.delete(p);audit.log(userId,"DELETE_PAYMENT_PLAN","PAYMENT_PLAN",id,Map.of());}
 private PlanResponse response(PaymentPlan p,List<PaymentTransaction> txs){return new PlanResponse(p.getId(),p.getOrderId(),p.getTotalAmount(),p.getMaxPerPayment(),p.getNumberOfPayments(),p.getDescription(),p.getReceiverType(),p.getReceiver(),p.getReceiverName(),p.getStatus(),p.getCreatedAt(),p.getUpdatedAt(),txs.stream().map(this::item).toList());}
 private PaymentItem item(PaymentTransaction x){return new PaymentItem(x.getId(),x.getSequence(),x.getAmount(),x.getStatus(),x.getQrPayload(),x.getCreatedAt(),x.getCompletedAt());}
}
