import React, { useEffect, useMemo, useState } from "react";
import { Search, RefreshCw, Eye } from "lucide-react";
import { api, unwrap } from "../services/api";
import PageTitle from "../components/PageTitle";
import StatusBadge from "../components/StatusBadge";

export default function Transactions() {
  const [data, setData] = useState([]); const [q, setQ] = useState(""); const [status, setStatus] = useState("ALL"); const [date, setDate] = useState(""); const [page, setPage] = useState(1); const [sort, setSort] = useState("date"); const [selected, setSelected] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { setData(unwrap(await api.get("/transactions"))); } catch (e) { setError(e.response?.data?.message || "Unable to load transactions."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const rows = useMemo(() => { const filtered = data.filter((x) => (status === "ALL" || x.status === status) && (!date || String(x.createdAt || "").startsWith(date)) && `${x.id} ${x.paymentPlanId}`.toLowerCase().includes(q.toLowerCase())); return [...filtered].sort((a,b) => sort === "amount" ? Number(b.amount)-Number(a.amount) : new Date(b.createdAt)-new Date(a.createdAt)); }, [data,q,status,date,sort]);
  const pageSize=8, pages=Math.max(1,Math.ceil(rows.length/pageSize)), visible=rows.slice((page-1)*pageSize,page*pageSize);
  return <div className="content"><PageTitle title="Transaction History" subtitle="All simulated payment attempts." action={<button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button>}/>
    <section className="panel"><div className="filters"><div className="search"><Search size={17}/><input aria-label="Search transactions" placeholder="Search transaction or plan ID" value={q} onChange={(e)=>{setQ(e.target.value);setPage(1)}}/></div><select aria-label="Sort transactions" value={sort} onChange={(e)=>{setSort(e.target.value);setPage(1)}}><option value="date">Newest</option><option value="amount">Highest amount</option></select><select aria-label="Filter status" value={status} onChange={(e)=>{setStatus(e.target.value);setPage(1)}}><option value="ALL">ALL</option><option value="PENDING">PENDING</option><option value="SUCCESS">SUCCESS</option><option value="FAILED">FAILED</option></select><input aria-label="Filter date" type="date" value={date} onChange={(e)=>{setDate(e.target.value);setPage(1)}}/></div>
      {loading ? <div className="loading">Loading transactions…</div> : error ? <div className="error">{error}</div> : <div className="table-wrap"><table><thead><tr><th>Transaction ID</th><th>Plan ID</th><th>Amount</th><th>Sequence</th><th>Status</th><th>Created</th><th>Action</th></tr></thead><tbody>{visible.map((x)=><tr key={x.id}><td>{x.id}</td><td>{x.paymentPlanId}</td><td>₹{Number(x.amount).toLocaleString("en-IN")}</td><td>{x.sequence}</td><td><StatusBadge status={x.status}/></td><td>{x.createdAt ? new Date(x.createdAt).toLocaleString() : "—"}</td><td><button className="icon-btn" aria-label={`View ${x.id}`} onClick={()=>setSelected(x)}><Eye size={17}/></button></td></tr>)}{!visible.length&&<tr><td colSpan="7" className="empty">No matching transactions.</td></tr>}</tbody></table></div>}
      <div className="pagination"><button className="secondary" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} of {pages}</span><button className="secondary" disabled={page===pages} onClick={()=>setPage(page+1)}>Next</button></div>
    </section>
    {selected&&<div className="modal-backdrop" onMouseDown={(e)=>e.target===e.currentTarget&&setSelected(null)}><div className="pay-modal" role="dialog" aria-modal="true"><div className="modal-head"><div><span className="eyebrow">Transaction details</span><h2>{selected.id}</h2></div><button className="icon-btn" onClick={()=>setSelected(null)} aria-label="Close">×</button></div><div className="detail-grid"><b>Plan</b><span>{selected.paymentPlanId}</span><b>Amount</b><span>₹{Number(selected.amount).toLocaleString("en-IN")}</span><b>Sequence</b><span>{selected.sequence}</span><b>Status</b><span><StatusBadge status={selected.status}/></span><b>Created</b><span>{selected.createdAt ? new Date(selected.createdAt).toLocaleString() : "—"}</span><b>Updated</b><span>{selected.updatedAt ? new Date(selected.updatedAt).toLocaleString() : "—"}</span><b>Completed</b><span>{selected.completedAt ? new Date(selected.completedAt).toLocaleString() : "—"}</span></div></div></div>}
  </div>;
}
